fixtures:
  repositories:
    stdlib:
      repo: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '4.6.0'
    inifile:
      repo: 'git://github.com/puppetlabs/puppetlabs-inifile.git'
      ref: '1.3.0'
  symlinks:
    rhn: "#{source_dir}"
