name 'ericsson-rhn'
version '0.1.0'
source 'git://github.com/Ericsson/puppet-module-rhn.git'
author 'Ericsson'
license 'Apache License, Version 2.0'
summary 'put a summary here'
description 'put a description here'
project_page 'https://github.com/Ericsson/puppet-module-rhn'

dependency 'puppetlabs/stdlib', '3.2.x'
